table Sales
	lineageTag: feb37a5b-bb01-434d-883f-40de5bbaa528

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 30933102-692a-44be-9797-068fc93733ec
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 9c1bd56b-285a-4754-b867-7edda92e40a8
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 496e79e3-1293-4d50-a538-ae63a5f9b7d1
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 4db73476-e0b8-4c22-83de-7cb6f1866c88
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: e2e0cfa1-e978-45f8-a075-c3cf1bbff035
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: b07d7a06-0a85-49d5-bc6f-f5bdbb5f1906
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1fe34c0a-b1fe-4656-922f-168d83968205
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: int64
		formatString: 0
		lineageTag: 01c3e8d7-a753-4b78-a8fe-9ca76653fa49
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	column Formatted_date =
			
			VAR DateInt = Sales[DateKey]
			VAR Year = INT(DateInt / 10000)
			VAR Month = INT(MOD(DateInt, 10000) / 100)
			VAR Day = MOD(DateInt, 100)
			RETURN DATE(Year, Month, Day)
		formatString: General Date
		lineageTag: daabdf9f-f976-44fe-a24a-b36b02cd7aea
		summarizeBy: none

		variation Variation
			isDefault
			relationship: a79abe68-e8f3-4a20-b178-989ab4441325
			defaultHierarchy: LocalDateTable_334cf84a-2a17-4e32-922a-3778e6e3552b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NithishYE\Downloads\OrderDetails_Data\OrderDetails_Data\Sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"OrderID", Int64.Type}, {"DateKey", Int64.Type}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"RegionID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Quantity", Int64.Type}, {"SalesAmount", Int64.Type}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

