table SalesRep
	lineageTag: a51ccddc-0c39-479b-b0ec-b9d3962e68fd

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 9b912676-c42c-4ffc-9027-47375429b6ce
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column SalesRepName
		dataType: string
		lineageTag: e377965b-3ce5-41e1-8472-c02767a4a63b
		summarizeBy: none
		sourceColumn: SalesRepName

		annotation SummarizationSetBy = Automatic

	partition SalesRep = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NithishYE\Downloads\OrderDetails_Data\OrderDetails_Data\SalesRep.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"SalesRepID", Int64.Type}, {"SalesRepName", type text}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

